- name: Setup MongoDB yum Repository
  ansible.builtin.copy:
    src: mongodb.repos
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: installed

- name: updating mongodb listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

-name: start MongoDB
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: yes

