- name: Mongodb server setup
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing mongodb
    ansible.builtin.dnf:
      name: mongodb-org
      state: present

  - name: start mongodb service
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: replacing configuration file 
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restart mongodb service
    ansible.builtin.service:
      name: mongod
      state: restarted
