- name: Setup Erlang repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Setup rabbitmq repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install ErLang and RabbitMQ
  ansible.builtin.yum:
    name:
      - rabbitmq-server
      - erlang
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Add Application User
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present



