- name: setup mysqlrepo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disabling MySQL 8 Version
  ansible.builtin.shell: module disable mysql -y

- name: install Mysql 5.7
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Start mysql server
  ansible.builtin.systemd:
      name: mysqld
      state: started
      enabled: yes

- name: Set Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1