- name: update prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: update alerts configuration
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted