- name: Configure NodeJS Repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks:
      file: app-prereq.yml

- name: Install nodejs dependencies
  community.general.npm:
    path: /app

- name: schema setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml
  when: schema_type is defined

- name: systemd service
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

