#print_head "Configure NodeJS Repo"
#curl -sL https://rpm.nodesource.com/setup_lts.x | bash &>>${log_file}
#status_check $?
#
#print_head "Install NodeJS"
#yum install nodejs -y &>>${log_file}
#status_check $?
#
#app_prereq_setup
#
#print_head "Installing NodeJS Dependencies"
#npm install &>>${log_file}
#status_check $?
#
#systemd_setup
#
#schema_setup

- name: Configure NodeJS Repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks:
      file: app-prereq.yml

- name: Install nodejs dependencies
  community.general.npm:
    path: /app

- name: Schema Service
  ansible.builtin.import_tasks:
    file: schema_setup
    when: schema_setup is defined

- name: systemd service
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

