#print_head "copy SystemD Service File"
#cp ${code_dir}/configs/${component}.service /etc/systemd/system/${component}.service &>>${log_file}
#status_check $?
#
#sed -i -e "s/ROBOSHOP_USER_PASSWORD/${roboshop_app_password}/" /etc/systemd/system/${component}.service &>>${log_file}
#
#print_head "Reload SystemD"
#systemctl daemon-reload &>>${log_file}
#status_check $?
#
#print_head "Enable ${component} Service"
#systemctl enable ${component} &>>${log_file}
#status_check $?
#
#print_head "Start ${component} Service "
#systemctl restart ${component} &>>${log_file}
#status_check $?

- name: Copy Ststemd Service File
  ansible.builtin.copy:
    src: "{{ component.service }}"
    dest: /etc/systemd/system/{{ component }}.service

- name: Start Service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: yes
    daemon-reload: yes