{
 "title": "roboshop",
 "time": { "from": "2023-06-08T10:35:28.664Z", "to": "2023-06-08T10:37:16.446Z" },
 "panels": [
  {
   "title": "ServerUP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "100 - (avg by (name) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{exported_name=\"cart.service\",state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"catalogue.service\",state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"user.service\",state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"shipping.service\",state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"payment.service\",state=\"active\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "node_systemd_unit_state{exported_name=\"nginx.service\",state=\"active\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "100 - (((node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100)"
    }
   ]
  }
 ]
}