groups:
  - name: roboshop-service-alert
    rules:
    {% for component in components %}

    - alert: Service Down Alert - {{ component.name }}.service
      expr: node_systemd_unit_state{exported_name="{{ component.service_name }}.service",state="active"} < 1
      for: 30s
      labels:
        severity: critical
        appname: {{ component.name }}
      annotations:
        summary: Service Down on Some Server - Service Name - {{ component.name }}.service
    {% endfor %}